# Generated by Django 5.0.3 on 2024-07-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                ("barcode", models.CharField(max_length=40, unique=True)),
                ("date_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Servante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("phone", models.CharField(max_length=20)),
                ("date_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10000)),
                (
                    "caissier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Factures",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.CreateModel(
            name="FactureProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantiter", models.IntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyRestau.facture",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyRestau.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "FactureProduit",
                "verbose_name_plural": "FactureProduits",
            },
        ),
        migrations.AddField(
            model_name="facture",
            name="produits",
            field=models.ManyToManyField(
                through="MyRestau.FactureProduit", to="MyRestau.product"
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="servante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MyRestau.servante"
            ),
        ),
    ]
