# Generated by Django 5.0.3 on 2024-07-21 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyRestau", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="factureproduit",
            options={},
        ),
        migrations.RemoveField(
            model_name="facture",
            name="total",
        ),
        migrations.RemoveField(
            model_name="factureproduit",
            name="unit_price",
        ),
    ]
