# Generated by Django 5.0.3 on 2024-07-22 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "MyRestau",
            "0002_alter_facture_options_alter_factureproduit_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="caissier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="servante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="MyRestau.servante"
            ),
        ),
    ]
